import json
import re
import logging
from typing import List, Optional, Literal
from pydantic import BaseModel, ValidationError

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class Command(BaseModel):
    action: Literal[
        "forward", "backward", "stop", 
        "look_left", "look_right", "look_up", "look_down", 
        "speak", "ask"
    ]
    speed: Optional[int] = None
    angle: Optional[int] = None
    duration: Optional[float] = None
    text: Optional[str] = None

class VLMResponse(BaseModel):
    reasoning: str
    plan: List[str]
    status: Literal["running", "completed"]
    command: Command

class ActionParser:
    @staticmethod
    def clean_json_string(raw_text: str) -> str:
        """
        Removes markdown formatting like ```json and ``` if the VLM 
        accidentally wraps its output in them.
        """
        raw_text = raw_text.strip()
        
        match = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', raw_text)

        if match:
            return match.group(1)
            
        return raw_text

    @staticmethod
    def get_safe_fallback(error_msg: str) -> dict:
        """
        If everything fails, return a safe STOP command so the robot 
        doesn't crash or drive into a wall.
        """
        logger.error(f"PARSING FAILED: {error_msg}. Triggering emergency stop.")
        return {
            "reasoning": f"System error: {error_msg}. Triggering safe fallback.",
            "plan": ["Stop immediately", "Wait for new instruction"],
            "status": "completed",
            "command": {
                "action": "stop",
                "speed": None,
                "angle": None,
                "duration": None,
                "text": None
            }
        }

    @classmethod
    def parse(cls, vlm_output: str) -> dict:
        """
        Main entry point to parse, clean, and validate VLM text.
        Returns a guaranteed safe dictionary to send via ZeroMQ.
        """
        # 1. Clean the string
        cleaned_text = cls.clean_json_string(vlm_output)
        
        # 2. Try parsing as JSON
        try:
            parsed_dict = json.loads(cleaned_text)
        except json.JSONDecodeError as e:
            return cls.get_safe_fallback(f"Invalid JSON generated by model: {e}")
            
        # 3. Validate against our strictly typed Pydantic schema
        try:
            validated_data = VLMResponse(**parsed_dict)
            return validated_data.model_dump()
        except ValidationError as e:
            # If the LLM hallucinated a wrong key or wrong data type (e.g., speed="fast" instead of 50)
            return cls.get_safe_fallback(f"Schema mismatch: {e}")
